### ISSUE TITLE
Deprecate AWS::Diagram::Group

### ISSUE THREAD

**Issue by ugwis** [awslabs/diagram-as-code#64]
## Why
The main difference between groups and resources was whether they had children. However, I found that there are many icons that can be used as both groups and resources. (For example, `AWS::ECS::Cluster` etc.). 

## What
The difference between the group implementation and the resource implementation was not large, and similar implementations were wrapped in an interface. Since we found no concerns about migrating to the Resource type, we will abolish the Group type and adopt a method that changes the rendering method of the Resource type depending on the presence or absence of children.
This allows users to use CFn like types without worrying about group/resource differences.

```[tasklist]
### Tasks
- [x] 1. Migrate to `AWS::Diagram::Resource`
- [x] 2. Remove Node interface
- [x] 3. Deprecate `AWS::Diagram::Group`
```

**Comment by ugwis** [comment]
Migration to Resource is complete. Wait a while before deleting Interface and abolishing AWS::Diagram::Group.

**Comment by ugwis** [comment]
Deprecated AWS::Diagram::Group
